
cc_library(
    name = "Common",
    srcs = ["event.cpp", "log.cpp"],
    hdrs = ["irenderer.h", "event.h", "log.h", "common.h", "player.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
